version: '3.7'

services:
  app:
    container_name: core-py-twitter
    build:
      context: ./core-twitter
      dockerfile: app.Dockerfile
    restart: on-failure
    volumes:
      - ./csv:/app/csv
    env_file:
      - ./env/.env
    ports:
      - 80:80
    entrypoint: ["sh", "-C", "/scripts/start.sh"]
    